<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meu curriculo</title>
</head>
<body>
  <img src="C:\Users\PC\Downloads\Screenshot_20240309-222427.png" width="130" height="180"/>
  <p><h1>Thauane Soares Vargas</h1></p> 
  <p><h4>Data de nascimento: 23/04/2001 - 22 anos</h4></p>
  <p><h4>Brasileira - Solteira</h4></p>
  <p><h4>Endereço: Estrada Piraui, Sítio São Jorge, num°: 10391</h4></p>
  <p><h4>Contato: (24) 992098151</h4></p>
  <p><h4><Thauanevargas@gmail.com</sub></h4></p>
  <p>




  </p>
<p><p3> <b>- Formação acadêmica -</b> </p3></p>
<p>Ensino 2 grau completo ( CIEP 297 ), ano finalizado: 2020</p>
<p>Engenharia de Software cursando ( Universidade Severino Sombra ), iniciado 2023</p>

<p><p4><b> - Experiencia profissional -</b></p><p/4></p>
<p>Função : Babá - 3 anos</p>
<p>Função : Recepcionatista - 3 anos ( atualmente trabalhando ).</p>
<p></p>
<p></p>
<p></p>
<p></p>

<p><b> Objetivo</b></p>
<p>Quero desenvolver minhas habilidade. Em busca de uma oportunidade para desenvolver e melhorar meus conhecimentos, e também algo que possa me instruir de forma crescente e contínua, visando sempre o crescimento entre mim e a empresa.</p>
</body>
</html>
